# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  title = "李 勇"
  [zh.params]
    description = "Site description in Chinese..."
  [[zh.menu.main]]
    name = "关于"
    url = "#about"
    weight = 1

  [[zh.menu.main]]
    name = "技能"
    url = "#skills"
    weight = 21

  [[zh.menu.main]]
    name = "实习经验"
    url = "#experience"
    weight = 31

  [[zh.menu.main]]
    name = "项目"
    url = "#projects"
    weight = 40

  [[zh.menu.main]]
    name = "奖项"
    url = "#projects"
    weight = 50
    
  [[zh.menu.main]]
    name = "领英"
    url = "https://www.linkedin.com/in/yong-li-8322551a0"
    weight = 51

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
  [[zh.menu.main]]
      name = "简历"
      url = "files/cv.pdf"
      weight = 70
